version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  example:
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - redis.uri=redis://redis
    command: ["./bin/redis"]
